// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq18w7ynn0e071wPHYX8f5aHqVFMtgnXQ',
    appId: '1:984152402925:web:1b716655ab9962592ed5e4',
    messagingSenderId: '984152402925',
    projectId: 'omnix-7caf5',
    authDomain: 'omnix-7caf5.firebaseapp.com',
    storageBucket: 'omnix-7caf5.firebasestorage.app',
    measurementId: 'G-7WP8370V2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoLICai-NWFvgQatv_G36a1LqbsjnYxVw',
    appId: '1:984152402925:android:f7f87ba7194d02c02ed5e4',
    messagingSenderId: '984152402925',
    projectId: 'omnix-7caf5',
    storageBucket: 'omnix-7caf5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHxx_DGfLbTXQz5N1nRrRhYo_yfNocxXA',
    appId: '1:984152402925:ios:c3848bb23791c72d2ed5e4',
    messagingSenderId: '984152402925',
    projectId: 'omnix-7caf5',
    storageBucket: 'omnix-7caf5.firebasestorage.app',
    iosBundleId: 'com.omnix.omnixApp',
  );
}
